# See https://cloud.google.com/appengine/docs/flexible/nodejs/configuring-your-app-with-app-yaml
# and https://cloud.google.com/appengine/docs/flexible/nodejs/reference/app-yaml for more info

runtime: nodejs10
service: default

# The settings below are to reduce costs during testing and not appropriate for production use.
# You would obviously want to increase the values for computing resources and look into auto scaling when running production workloads.

basic_scaling:
  max_instances: 1

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

beta_settings:
  # The connection name of your instance, available by using
  # 'gcloud beta sql instances describe [INSTANCE_NAME]' or from
  # the Instance details page in the Google Cloud Platform Console.
  cloud_sql_instances: co-presenter-247006:europe-west1:co-presenter-db
